In [1]:
import numpy as np

In [9]:
arr2D = np.array ([[1,2,3], [4,5,6], [7,8,9]])
print(arr2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# sum of 2D array:
print(np.sum(arr2D))

45


In [11]:
# Row/Column wise sum using axes     -  more about axes in handwritten notes

print(np.sum(arr2D, axis=0)) # Row wise provide sum in vertical direction

[12 15 18]


## 3D Array: 

In [12]:
arr = np.array([[[1,2], [3,4], [5,6]]  , [[7,8], [9,10], [11,12]] ])  #2X2X3 - two 2D arrays of 2x3