# Principal Component Analysis (PCA)

PCA stands for **Principal Component Analysis**.

It is a dimensionality reduction technique that : 
- Combines features
- Reduces dimensions
- Keeps maximum information

#  Intuition Example (OTT Platform)

Suppose we are analyzing user engagement on an OTT platform.

We have these features:

- Number of shows watched per week
- Average watch time (minutes)
- % completion rate

These 3 features together represent:

 USER ENGAGEMENT

Instead of keeping 3 features,
can we combine them into 1 strong feature?

YES — PCA does exactly this.

# Step 1️⃣: Spread of Data (Variance)

PCA looks at:

👉 Where is the data spread the most?

Because:
More spread = More information
Less spread = Less information

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Create simple 2D dataset
np.random.seed(42)

x = np.random.normal(5, 2, 100)
y = 2*x + np.random.normal(0, 2, 100)

plt.scatter(x, y)
plt.xlabel("Feature 1 (Avg Watch Time)")
plt.ylabel("Feature 2 (Completion Rate)")
plt.title("Spread of Data")
plt.show()

Notice the data is spread diagonally.

That diagonal direction contains most of the information.

PCA finds that direction automatically.

# Step 2: cent6er around mean

Before applying PCA:

We shift the data so that mean becomes 0.

Why?

Because PCA works on variance,
and variance is measured around the mean.

In [4]:
from sklearn.preprocessing import StandardScaler

data = np.column_stack((x, y))

scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)

data_scaled[:5]

array([[ 0.66461921, -0.12300204],
       [-0.03808894, -0.26611539],
       [ 0.83169721,  0.59175748],
       [ 1.80040643,  1.26310688],
       [-0.14420598, -0.23097475]])

# Step 3️⃣: Best Fit Line (Principal Component 1)

Now PCA finds:

👉 A best fit line through the data
👉 In the direction of maximum spread

This line is called:

⭐ Principal Component 1 (PC1)

It is calculated using:
- Eigenvectors
- Eigenvalues

In [5]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
pca.fit(data_scaled)

print("Principal Components:")
print(pca.components_)

print("\nVariance captured:")
print(pca.explained_variance_ratio_)

Principal Components:
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]

Variance captured:
[0.93620214 0.06379786]


# Step 4️⃣: Projection

Now we project all points onto PC1.

Instead of using:

Feature1, Feature2

We use:

👉 Projected Value on PC1

This becomes our new feature.

In [7]:
# Reduce to 1 dimension
pca_1d = PCA(n_components=1)
reduced_data = pca_1d.fit_transform(data_scaled)

reduced_data[:5]

array([[ 0.38298118],
       [-0.21510495],
       [ 1.00653447],
       [ 2.16623103],
       [-0.26529284]])

Now 2 features → 1 feature

This new feature is a linear combination of:

F1 and F2

This is Principal Component 1.

## What is PC2?
🟦 Markdown Cell
PC2 is:

👉 A line perpendicular to PC1
👉 Captures the remaining variance

Important:
PC1 and PC2 are always orthogonal (90° apart).